version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - mvn -X -f demoall/pom.xml clean
  build:
    commands:
      - echo Build started on `date`
      - mvn -f demoall/pom.xml -DskipTests install
  post_build:
    commands:
      - mv demoweb/target/demoweb.war demoweb.war
      - mkdir .ebextensions
      - mv demoweb/.ebextensions/* .ebextensions/
      - echo Build completed on `date`

artifacts:
  files:
    - demoweb.war
    - .ebextensions/**/*
