version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - mvn -f demoall/pom.xml clean
  build:
    commands:
      - echo Build started on `date`
      - mvn -f demoall/pom.xml install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - demoweb/target/demoweb.war
    - move-war.sh
  discard-paths: yes
    
    
