USE application;

CREATE TABLE `INSTRUMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SYMBOL` varchar(5) NOT NULL,
  `EXCHANGE` varchar(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SYMBOL_UNIQUE` (`SYMBOL`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `INSTRUMENT_INFO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSTRUMENT_ID` int(11) NOT NULL,
  `DATE` date NOT NULL,
  `OPEN_PRICE` varchar(45) NOT NULL,
  `CLOSE_PRICE` varchar(45) NOT NULL,
  `VOLUME` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INSTR_ID_FK_idx` (`INSTRUMENT_ID`),
  CONSTRAINT `INSTR_ID_FK` FOREIGN KEY (`INSTRUMENT_ID`) REFERENCES `INSTRUMENT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
